### PR TITLE
Requests 'fix' + directory specify

### PR DESCRIPTION
**Pull request by ChatDisabled**

### CODE REVIEW

**Comment by ChatDisabled** [comment]
https://github.com/K3YOMI/CFX-SCRAPER/blob/0a231fae8633556c41607816092c476a240f938a/CFX.re-Scraper/Javascript/NodeForum.js#L2 still refers to the `request` module and changing to `requests` would need a change of code of which I don't have the knowledge for. Also is it just me or do you get "Missing file / directory" errors since it runs from the base python file located in the main directory?

Furthermore, pretty sure https://github.com/K3YOMI/CFX-SCRAPER/blob/main/CFX-ScraperBase/_index.js isn't used at all and the whole dir can be removed since I moved the bat file over to the correct directory (either in Javascript or one above works).

I might be crazy let me know, please don't bully me :(

**Comment by K3YOMI** [comment]
# CFX.re Scraper
### Python Package Install Failure
Hello *Chat*, thank you for reaching out about the issues you have been having. I recently made a mistake in the *_install.py* python script where it would install the *wrong* package. I did do a revert and added a few log messages
```py
    os.system('npm i request --prefix ./Javascript') # Fixed Requests => Request [Must run in the __init.py dir)
    os.system('cls || clear')
    log("Ignore the [npm WARN] messages. They are not important.") # Ignore the log messages within the npm install
```
### Directory Issues / _index.js utilizations 
The directory issue you have been having is quite a simple fix. I could implement a workaround in the future, but for now. 
You *must* be in the **CFXre-Scraper** directory *(where __init.py is located)*. I haven't gotten any *"missing file/directory"* errors. I'll keep an eye on that. In addition, the *__index.js* located in the (*ScraperBase*) Directory is only used if you want to make a custom script for the scraper. It's meant for those people who want to make something out of the scraper instead of wait for an update to be pushed for their features.

**Comment by ChatDisabled** [comment]
Have it your way then old man!

**Comment by K3YOMI** [comment]
> Have it your way then old man!

:)

**Pull request closed without merging**
